# Generated by Django 4.0.8 on 2023-05-16 22:12

from django.conf import settings
from django.db import migrations
from django.db import models
from django.db.migrations.operations.base import Operation
from typing import List

import django.db.models.deletion
import hashid_field.field


def set_is_online_attribute_on_user_chat_model(apps, _schema_editor):
    """
    Since we are moving the 'is_online' attribute of the RoomUser model onto the UserChat model,
    we should not disrupt users who are currently online. Therefore, we create UserChat objects
    for users who are currently online and set their 'is_online' attribute to True.
    """
    # fetching the RoomUser and UserChat models
    RoomUser = apps.get_model("df_chat", "RoomUser")
    UserChat = apps.get_model("df_chat", "UserChat")

    users_who_are_currently_online = (
        RoomUser.objects.filter(is_online=True)
        .values_list("user", flat=True)
        .distinct()
    )
    for user_id in users_who_are_currently_online:
        UserChat.objects.get_or_create(user_id=user_id, is_online=True)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("df_chat", "0001_initial"),
    ]

    # 1. Create a UserChat model with an 'is_online' field.
    # 2. Create UserChat objects for users who are currently online.
    # 3. Remove the 'is_online' field from the RoomUser model.
    operations: List[Operation] = [
        migrations.CreateModel(
            name="UserChat",
            fields=[
                (
                    "id",
                    hashid_field.field.BigHashidAutoField(
                        alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        auto_created=True,
                        min_length=13,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_chat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            set_is_online_attribute_on_user_chat_model, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="roomuser",
            name="is_online",
        ),
    ]
